#ifndef SCHRODINGER_FORMULA_CONSTANTS_H
#define SCHRODINGER_FORMULA_CONSTANTS_H

#define MATSLISE_HMAX_delta 17
#define MATSLISE_ETA_delta 9
#define MATSLISE_ETA_h 10
#define MATSLISE_N 16

#define MATSCS_HMAX_delta 10
#define MATSCS_ETA_delta 5
#define MATSCS_ETA_h 6
#define MATSCS_N 9

#define MATSLISE2D_DELTA_V_DEGREE 8


#endif
